### ISSUE TITLE
Issues with Users that have a "Umlaut" eg. Ö or ß

### ISSUE THREAD

**Issue by janhoelscher** [ansibleguy76/ansibleforms#142]
**Describe the bug**
I have configured authentication via an Active Directory Server. Users without a german "Umlaut" can login without any problems. 
But users with an "Umlaut" in there CN getting "Ldap: Invalid Credentials" as a response on the login page. 
It has been double checked with two users having this issue. 

**To Reproduce**
1. Configuring Active Directory Server in Ldap Config
2. Try to login as a user which have an "Umlaut" in their CN
3. Getting error message on login page

**Expected behavior**
User should login without any errors.

**Version**
ansibleforms v5.0.0

**Deployment**
Deployed ansibleforms with :
- docker-compose

**Additional context**
Logs only shows error: Error connecting to `ldap : Invalid Credentials but credentials` are correct.

Full DN from user account look similar than this `CN=<here is sAMAccountName>_(<forename>_<surname>),OU=user,OU=<censored>,DC=<censored>,DC=<censored>,DC=de` as `<surname>` contains an "Ö"

**Comment by ansibleguy76** [comment]
I have investigated.
Basic authentication was not handling utf8 characters, that will be fixed in 5.0.1
The user now arrives correctly at the server end, unfortunately, I have found a correct way to encode the username so ldap is happy.  I tried hex encoding, for example  "\00\FC" => ü, but that didn't work.  So for the moment I don't know how to fix it.  I'm using the ldapjs library which is up to date.  Maybe I need to encode the username when sending to ldap, but need to find how and then I can fix this.  TBC

**Comment by ansibleguy76** [comment]
found it... and fixed in 5.0.1

**Comment by ansibleguy76** [comment]
> Maybe I need to encode the username when sending to ldap, but need to find how and then I can fix this. 

I had to decode instead, ldap return encoded Distinguished name and to bind ldap, I must send utf8, so had to build an unescape function.

(https://github.com/ldapjs/node-ldapjs/issues/968)

**Comment by qfdk** [comment]
Hello @ansibleguy76 

Thanks for your workaround. It works for ldap.js.

Have a nice day.
