### ISSUE TITLE
error: [ansibleforms] Query error : Error: Unknown column 'use_credentials' in 'field list' 

### ISSUE THREAD

**Issue by birb57** [ansibleguy76/ansibleforms#199]
Hi

I am trying to use your tool but I got issue configuring awx connection

when I try to configure awx connection with credential (login/password) I get below error message when I "Update AWX" :

error: [ansibleforms] Query error : Error: Unknown column 'use_credentials' in 'field list'

Thanks for your support

To reproduce try to configure an awx connection

When try to update AWX connection:
Failed to update awx, Error: Unknown column 'use_credentials' in 'field list'

Build v5.0.3

**Comment by ansibleguy76** [comment]
I will look into it. 
Thank you for reporting

**Comment by ansibleguy76** [comment]
The docker compose project is updated.
The use_credentials was indeed not present in the init script.
This usually get's fixed in the code when it starts, but I cleaned up some older database patches and seems like that was one of them.  In your case you will need redeploy or wait for the new release, where I will reintroduce the patch.

**Comment by ansibleguy76** [comment]
5.0.4 beta (alias ansibleguy/ansibleforms:beta) is being pushed.  You will need to change the image to beta, pull the image and rebuild the container.  If all is well, the use_credentials patch will be applied.
